### ISSUE TITLE
fatal error: avr/io.h: No such file or directory

### ISSUE THREAD

**Issue by EagleSmith** [spaniakos/Cryptosuite#10]
i used arduino 1.6.10 ,board is esp8266

C:\Users\Eagle\Documents\Arduino\libraries\Sha/sha1_config.h:28:21: fatal error: avr/io.h: No such file or directory

can you fix this problem?
thanks.

**Comment by spaniakos** [comment]
as it seems esp8266 is a non avr board. (thats the info i get from your error)
for that i need your board code (ARDUINO_ARCH_ESP8266) maybe ? if this is the board code (you can see that when you compile a sketch, 

after that , you need to add this into appropriate sections in every _config.h file, in order fot your board to load the correct headers.

i am not able to test this changes as i dont have esp8266 board. i need your help on that.
the first change i propose is :
#if  (defined(__linux) || defined(linux)) || defined(__ARDUINO_X86__) || defined(ARDUINO_ARCH_ESP8266)
on line 16 in sha1_config.h
and on line 17 in sha256_config.h

thanks
spaniakos

**Comment by EagleSmith** [comment]
thank you.
this is the esp8266  code for arduino:
https://github.com/esp8266/Arduino

**Comment by markrad** [comment]
Hi @spaniakos,

I had the same isssue. Rather than just point you at all the ESP8266 code I **actually** tried your suggestion. I'm happy to report that it does resolve the issue on the ESP8266. Do you think you could push that change for me?

If you really want, I will send you a pull request but it is only two lines and much less hassle for you.

Thank you!

_Mark Radbourne MSFT_

**Comment by spaniakos** [comment]
sure, 

thank you for the support
if you make a pull request i will revise the code and publish it
OR
just sent me the changes and i will push them my self.

Thank you

**Comment by markrad** [comment]
The changes were exactly as you suggested to the original commenter:

```
#if (defined(linux) || defined(linux)) || defined(__ARDUINO_X86) || defined(ARDUINO_ARCH_ESP8266)
```
on line 16 in sha1_config.h
and on line 17 in sha256_config.h

This was all I did and it compiled without issue.
