### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by flacidsnake** [spaniakos/Cryptosuite#15]
Hi,

thank you for this fork. Could you tell me which license applies or maybe add a disclaimer at the readme file?

Thanks in advance.
Regards.

**Comment by spaniakos** [comment]
Hello there
Will add it tomorrow noon Greece time
Thank you

**Comment by spaniakos** [comment]
license applied.

Thank you

https://github.com/spaniakos/Cryptosuite/blob/master/LICENSE.txt
