### ISSUE TITLE
How to obtain the original string?

### ISSUE THREAD

**Issue by Papa-Tori** [spaniakos/Cryptosuite#16]
Hi,
the library works pretty well hashing strings, but, how can I do the reverse process? I mean, obtain the original string using the key and the hash.

Regards.

P.S.: Thank you for adding the license!

**Comment by spaniakos** [comment]
Hash functions are one way functions.
It's not encryption decryption algorithm.
You only hash on server and rehash in client to check the validity of the
data.
If you want encryption decryption algorithms check my other repos.

**Comment by Papa-Tori** [comment]
Thank you for your fast reply! I'll check your AES library.

**Comment by spaniakos** [comment]
No problem
