### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by budnail** [spaniakos/Cryptosuite#4]
Could you assign a license to Cryptosuite, so that those of us down stream can use it appropriately?
BSD, Apache, or MIT would be my preference, but LGPL would be fine too.  But it's your code ( I think) so whatever you feel comfortable with.  I plan to use it with Particle.io's Photon and Electron devices.  Before I can share my port with that community I believe I'm required to assign it a license.  Of course it must be compatible with your license since that is where most of the work was done.

**Comment by spaniakos** [comment]
Sure, i will assign a license but i need some time for it. I don't have my
laptop with me this week. I will try to do it on Wednesday.

**Comment by budnail** [comment]
Thanks.
